### ISSUE TITLE
special object shelf.Request injection

### ISSUE THREAD

**Issue by SatWiz** [dart-bridge/dart-bridge.github.io#4]
I try to workout the example in the dependency injection about the self.Request part.

I really have no idea how and where to put the injection part to use the special object shelf.Request and the editor is not hint to also. 

Can you please explain a bit more?

**Comment by emilniklas** [comment]
[Shelf](https://pub.dartlang.org/packages/shelf) is another package, which handles HTTP middleware for Bridge. Since it's used in _bridge.http_, it's already included in you packages directory. So in your controller (or wherever you're trying to inject the request), put this import at the top (or in the library that your script is a part of):

``` dart
import 'package:shelf/shelf.dart' as shelf;
```

The `as shelf` part means that everything that's included in the package are available under the alias `shelf`, making `shelf.Request` available to you. If you like, you can omit the `as shelf` part:

``` dart
import 'package:shelf/shelf.dart';
```

And inject the request as `Request` instead of `shelf.Request`.

Here's an example with `api.dart` and a controller:

``` dart
// lib/api/api.dart
import 'package:bridge/http.dart';
import 'package:bridge/tether.dart';

import 'my_controller.dart';

class Api {
  MyController controller;

  Api(MyController this.controller);

  routes(Router router) {
    router.get('/', controller.index, name: 'index');
  }

  tether(Tether tether) {}
}
```

``` dart
// lib/api/my_controller.dart
import 'package:shelf/shelf.dart' as shelf;

class MyController {
  index(shelf.Request request) {
    return "You're requesting ${request.uri}";
  }
}
```

**Comment by emilniklas** [comment]
Note that the above example is not tested and might contain some errors, but I hope it answers your question.

**Comment by SatWiz** [comment]
got it, thanks very much!
